config/routes.rb
Pf::Application.routes.draw do
  # authenticated :user do
  # end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :submissions
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    can :read, :all
    can :manage, Submission, user_id: user.id
    # if user.id.present?
    #   can :create, :submission
    # end
    # if user.admin?
    #   can :manage, :all
    # else
    #   can :read, :all
    # end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user

  attr_accessible :description, :title

  validates :title, :description, :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :submissions

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  # check_authorization

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @submissions = Submission.accessible_by(current_ability)
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  load_and_authorize_resource

  # GET /submissions
  # GET /submissions.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @submissions }
    end
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @submission }
    end
  end

  # GET /submissions/new
  # GET /submissions/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @submission }
    end
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission.user = current_user

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render json: @submission, status: :created, location: @submission }
      else
        format.html { render action: "new" }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /submissions/1
  # PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update_attributes(params[:submission])
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy

    respond_to do |format|
      format.html { redirect_to submissions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/home/index.html.haml
%h1 Welcome to PFv2

%table
  %tr
    %th
    %th
    %th
    %th

  - @submissions.each do |submission|
    %tr
      %td= submission.title
      %td= link_to 'Show', submission
      %td= link_to 'Edit', edit_submission_path(submission)
      %td= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Submission', new_submission_path

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Pf", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Pf"
      %meta{:content => content_for?(:description) ? yield(:description) : "Pf", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    #container.container
      %header
        = render 'layouts/navigation'
        = render 'layouts/messages'
      #main{:role => "main"}
        = yield
      %footer
    / ! end of #container

app/views/submissions/_form.html.haml
= simple_form_for(@submission) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description

  .form-actions
    = f.button :submit

app/views/submissions/edit.html.haml
%h1 Editing submission

= render 'form'

= link_to 'Show', @submission
\|
= link_to 'Back', submissions_path

app/views/submissions/index.html.haml
%h1 Listing submissions

%table
  %tr
    %th
    %th
    %th

  - @submissions.each do |submission|
    %tr
      %td= link_to 'Show', submission
      %td= link_to 'Edit', edit_submission_path(submission)
      %td= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Submission', new_submission_path

app/views/submissions/new.html.haml
%h1 New submission

= render 'form'

= link_to 'Back', submissions_path

app/views/submissions/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_submission_path(@submission)
\|
= link_to 'Back', submissions_path

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}